"""
SLO Gate — run via `make slo-gate`

Compares reports/slo_metrics.json against configs/alert_thresholds.yaml.
Fails CI if any SLO threshold is breached.

In production, slo_metrics.json is generated by the monitoring pipeline.
In CI, it uses a fixture that simulates a healthy deployment.
"""
import json
import pathlib
import pytest
import yaml

ROOT       = pathlib.Path(__file__).parent.parent
SLO_FILE   = ROOT / "reports" / "slo_metrics.json"
THRESHOLDS = ROOT / "configs" / "alert_thresholds.yaml"


@pytest.fixture(scope="module")
def slo():
    with open(SLO_FILE) as f:
        return json.load(f)


@pytest.fixture(scope="module")
def thresholds():
    with open(THRESHOLDS) as f:
        return yaml.safe_load(f)


# ── SLO Gates ─────────────────────────────────────────────────────────────────

def test_SLO1_availability(slo, thresholds):
    """SLO-1: Availability must meet monthly target."""
    actual    = slo["availability_pct"]
    threshold = thresholds["slo"]["availability_pct"]
    assert actual >= threshold, (
        f"[SLO-1] Availability {actual}% < {threshold}% target"
    )


def test_SLO2_latency_p95(slo, thresholds):
    """SLO-2: p95 latency must stay within budget."""
    actual    = slo["latency_p95_ms"]
    threshold = thresholds["slo"]["latency_p95_ms"]
    assert actual <= threshold, (
        f"[SLO-2] p95 latency {actual}ms > {threshold}ms threshold"
    )


def test_SLO3_latency_p99(slo, thresholds):
    """SLO-3: p99 latency must stay within hard limit."""
    actual    = slo["latency_p99_ms"]
    threshold = thresholds["slo"]["latency_p99_ms"]
    assert actual <= threshold, (
        f"[SLO-3] p99 latency {actual}ms > {threshold}ms threshold"
    )


def test_SLO4_error_rate(slo, thresholds):
    """SLO-4: Error rate must stay below threshold."""
    actual    = slo["error_rate_pct"]
    threshold = thresholds["slo"]["error_rate_pct"]
    assert actual < threshold, (
        f"[SLO-4] Error rate {actual}% >= {threshold}% threshold"
    )


def test_SLO5_timeout_rate(slo, thresholds):
    """SLO-5: Timeout rate must stay below threshold."""
    actual    = slo["timeout_rate_pct"]
    threshold = thresholds["slo"]["timeout_rate_pct"]
    assert actual < threshold, (
        f"[SLO-5] Timeout rate {actual}% >= {threshold}% threshold"
    )


def test_SLO6_coverage(slo, thresholds):
    """SLO-6: Coverage (non-uncertain predictions) must meet threshold."""
    actual    = slo["coverage"]
    threshold = thresholds["slo"]["coverage"]
    assert actual >= threshold, (
        f"[SLO-6] Coverage {actual:.2%} < {threshold:.2%} threshold"
    )


def test_SLO7_prediction_drift(slo, thresholds):
    """SLO-7: Prediction distribution drift must not exceed KS threshold."""
    actual    = slo["prediction_drift_ks"]
    threshold = thresholds["slo"]["prediction_drift_ks"]
    assert actual < threshold, (
        f"[SLO-7] Prediction drift KS={actual:.3f} >= {threshold:.3f} — "
        "possible data drift, ML team review required"
    )
